done
learn-academy-2021-bravo/week-5-assessment-Vivean28 pull request #1
Opened 2021-06-07 16:08 UTC by Vivean28

2021-06-07 17:01 UTC, WalkerTexas-coder requested changes
You have 4 versions of the function "converter" select the one you want me to look over as your final approach and comment out the others. That or incorporate them together, your call.

2021-06-09 18:13 UTC, WalkerTexas-coder approved these changes
Okay Vivean, what you submitted would be a good practice sheet, but this isn't the kind of code you'd want to submit for a Pull Request or an Assessment/ interview of your coding skills. I can see you worked very hard on this and I appreciate it. Organizing / cleaning up our code as well as showing our logic is important. I am approving this code but the next assessment I will be expecting functional and clean code. Where you struggle to make the code functional I will expect documentation regarding where you got stuck and how you tried to solve the issue.

2021-06-09 18:13 UTC, WalkerTexas-coder commented on rails-questions.md
> +$ rails g model meals meals_breakfast:string meals_lunch:string meals_dinner:string
the first Meals will need to be uppercase (just the "M")

2021-06-09 18:13 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +        expect(coverter(secretCodeWord3)).toEqual("Eccentric")
So your third test here is checking for the wrong answer, just a heads up!

2021-06-09 18:13 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +
Okay, theres so much going on here I'm not sure where to start a review on "converter." I appreciate you practiced your functions, but pushing up multiple functions of the same name is not a habit we want to fall into. This would potentially  break a code base if it was to be merged into a larger project. There are number of small logical issues in each of these four "converters."  I would like to know if these four could be combined refactored into functioning code.

2021-06-09 18:13 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +console.log(fullHouse(hand1))
So Line 284 here is returning nothing. Even if we have the correct logic we'll never know it if we don't return something.

2021-06-10 13:20 UTC, Vivean28 commented
I can meet you now

On Wed, Jun 9, 2021 at 11:13 AM Austin Walker ***@***.***>
wrote:

> *@WalkerTexas-coder* approved this pull request.
>
> Okay Vivean, what you submitted would be a good practice sheet, but this
> isn't the kind of code you'd want to submit for a Pull Request or an
> Assessment/ interview of your coding skills. I can see you worked very hard
> on this and I appreciate it. Organizing / cleaning up our code as well as
> showing our logic is important. I am approving this code but the next
> assessment I will be expecting functional and clean code. Where you
> struggle to make the code functional I will expect documentation regarding
> where you got stuck and how you tried to solve the issue.
> ------------------------------
>
> In rails-questions.md
> <https://github.com/learn-academy-2021-bravo/week-5-assessment-Vivean28/pull/1#discussion_r648539935>
> :
>
> >
>
>  4. What is the command to generate a Rails model for a meals table with columns named breakfast, lunch, and dinner?
> -
> +$ rails g model meals meals_breakfast:string meals_lunch:string meals_dinner:string
>
> the first Meals will need to be uppercase (just the "M")
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2021-bravo/week-5-assessment-Vivean28/pull/1#discussion_r648543112>
> :
>
> > @@ -16,38 +18,234 @@
>  // --------------------1) Create a function that takes in a string and returns a coded message. The coded message converts 'a' to 4, 'e' to 3, 'i' to 1, and 'o' to 0.
>
>  // a) Create a test with an expect statement using the variables provided.
> -
> +describe("coverter", () =>{
> +    var secretCodeWord1 = "Lackadaisical"
> +    // Expected output: "L4ck4d41s1c4l"
> +    var secretCodeWord2 = "Gobbledygook"
> +    // Expected output: "G0bbl3dyg00k"
> +    var secretCodeWord3 = "Eccentric"
> +    // Expected output: "3cc3ntr1c"
> +    it("return coverte 'a' to 4, 'e' to 3, 'i' to 1, and 'o' to 0.", () =>{
> +        expect(coverter(secretCodeWord1)).toEqual("L4ck4d41s1c4l")
> +        expect(coverter(secretCodeWord2)).toEqual("Gobbledygook")
> +        expect(coverter(secretCodeWord3)).toEqual("Eccentric")
>
> So your third test here is checking for the wrong answer, just a heads up!
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2021-bravo/week-5-assessment-Vivean28/pull/1#discussion_r648548746>
> :
>
> > +
> +
> +//this worked but now I have to change evry a
> +// var secretCodeWord1 = "Lackadaisical"
> +//a is my search value and 4 is what I want to replcae it with
> +//  secretCodeWord1.replace("a", 4)
> +// "L4ckadaisical"
> +
> +
> +//THIS WORKED
> +// var secretCodeWord1 = "Lackadaisical"
> +// secretCodeWord1.replace(/a/g, 4)
> +//Here I used regulare expretion and the /a/g the g in the end stands for globale
> +//"L4ck4d4isic4l"
> +
> +
>
> Okay, theres so much going on here I'm not sure where to start a review on
> "converter." I appreciate you practiced your functions, but pushing up
> multiple functions of the same name is not a habit we want to fall into.
> This would potentially break a code base if it was to be merged into a
> larger project. There are number of small logical issues in each of these
> four "converters." I would like to know if these four could be combined
> refactored into functioning code.
> ------------------------------
>
> In code-challenges.test.js
> <https://github.com/learn-academy-2021-bravo/week-5-assessment-Vivean28/pull/1#discussion_r648551730>
> :
>
> > -// Expected output: true
> -var hand2 = [5, 5, 3, 3, 4]
> -// Expected output: false
> -var hand3 = [5, 5, 5, 5, 4]
> -// Expected output: false
> +const fullHouse = (array) =>{
> +  let sameArray = []
> +  for(let i = 0; array.length; 1++){
> +      if(array[i] == 5 && array[i] ==2){
> +
> +      }
> +  }
> +  return
> +}
> +
> +console.log(fullHouse(hand1))
>
> So Line 284 here is returning nothing. Even if we have the correct logic
> we'll never know it if we don't return something.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/learn-academy-2021-bravo/week-5-assessment-Vivean28/pull/1#pullrequestreview-679968454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQH7R3NE27ARKBZJH7O6D2LTR6VONANCNFSM46H7XSDQ>
> .
>

2021-06-22 04:32 UTC, merged